# Generated by Django 5.2.7 on 2025-10-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('deactivated', 'Deactivated'), ('activated', 'Activated'), ('completed', 'Completed')], default='deactivated', max_length=20),
        ),
    ]
