# Generated by Django 5.2.7 on 2025-10-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='status',
            field=models.CharField(choices=[('deactivated', 'Deactivated'), ('activated', 'Activated'), ('completed', 'Completed')], default='deactivated', max_length=20),
        ),
    ]
