# Generated by Django 5.2.7 on 2025-11-03 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='api.subevent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='api.subevent')),
            ],
            options={
                'verbose_name_plural': 'Criteria',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('type', models.CharField(choices=[('judge', 'Judge'), ('chairman', 'Chairman of the Board')], default='judge', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='api.subevent')),
            ],
            options={
                'ordering': ['type', 'order', 'id'],
            },
        ),
    ]
