"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import warnings

# Monkey-patch to bypass MariaDB version check
# This is a workaround for MariaDB 10.4 compatibility with Django 5.2
try:
    import django.db.backends.mysql.base
    _original_check_database_version_supported = django.db.backends.mysql.base.DatabaseWrapper.check_database_version_supported

    def _patched_check_database_version_supported(self):
        try:
            _original_check_database_version_supported(self)
        except Exception as e:
            # Only bypass if it's a version check error for MariaDB 10.4
            if 'MariaDB 10.5' in str(e) or 'MariaDB 10.4' in str(e):
                warnings.warn(f"Bypassing MariaDB version check: {e}", UserWarning)
                return
            raise

    django.db.backends.mysql.base.DatabaseWrapper.check_database_version_supported = _patched_check_database_version_supported
    
    # Disable RETURNING clause for MariaDB 10.4 compatibility
    # RETURNING is only supported in MariaDB 10.5+, but Django 5.2 uses it by default
    import django.db.backends.mysql.features
    django.db.backends.mysql.features.DatabaseFeatures.supports_returning = False
    
    # Patch the MySQL cursor execute method to strip RETURNING clauses
    # This is needed because MariaDB 10.4 doesn't support RETURNING
    import django.db.backends.mysql.base
    _original_cursor_execute = django.db.backends.mysql.base.CursorWrapper.execute
    
    def _patched_cursor_wrapper_execute(self, sql, params=None):
        # Remove RETURNING clause from SQL if present
        if isinstance(sql, str) and ' RETURNING ' in sql.upper():
            # Strip RETURNING clause and everything after it
            sql_parts = sql.split(' RETURNING ', 1)
            sql = sql_parts[0]
        return _original_cursor_execute(self, sql, params)
    
    django.db.backends.mysql.base.CursorWrapper.execute = _patched_cursor_wrapper_execute
except ImportError:
    # If MySQL backend is not available, skip patching
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j-3p8z=@a!8v2(&k-qin2)@1u#8)9tgr7(t@$cncc(d%_z3p96'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'backend.api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cjms_dbs',
        'USER':'root',
        'PASSWORD':'',
        'HOST':'localhost',
        'PORT':'3306',
        'OPTIONS': {
            # Workaround for MariaDB 10.4 compatibility
            # Django 5.2 requires MariaDB 10.5+, but we'll allow 10.4 for now
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}